namespace TF.EX.Domain.Models.State
{
    public struct MatchStats
    {
        public bool Won { get; set; }
        public bool GotWin { get; set; }
        public int PointsFromGoal { get; set; }
        public uint SpamShots { get; set; }
        public uint ArrowsShot { get; set; }
        public uint ArrowsCollected { get; set; }
        public uint ArrowsCaught { get; set; }
        public uint OwnArrowsCaught { get; set; }
        public uint ShieldsBroken { get; set; }
        public uint TreasuresTaken { get; set; }
        public uint Dodges { get; set; }
        public uint Jumps { get; set; }
        public uint CrownSpawns { get; set; }
        public uint FailedShots { get; set; }
        public uint ExplosionsSurvived { get; set; }
        public uint DeathsDuringDodgeCooldown { get; set; }
        public uint HatsShotOff { get; set; }
        public uint LedgeGrabbedKills { get; set; }
        public uint WinnerKills { get; set; }
        public uint BombMultiKill { get; set; }
        public uint ScreenWraps { get; set; }
        public uint ArrowScreenWraps { get; set; }
        public uint KillsWhileDead { get; set; }
        public uint CrownsPickedUp { get; set; }
        public uint HatsPickedUp { get; set; }
        public uint ArrowsStolen { get; set; }
        public uint RoundSweeps { get; set; }
        public uint FurthestBehind { get; set; }
        public uint MostBouncesLaserKill { get; set; }
        public uint DrillHits { get; set; }
        public uint DodgesTooLate { get; set; }
        public uint GracePeriodCatches { get; set; }
        public uint SelfLaserKills { get; set; }
        public long FastestKill { get; set; }
        public uint MostBoltTurns { get; set; }
        public uint DodgeStomps { get; set; }
        public uint TeamArrowCatches { get; set; }
        public uint KillsAsGhost { get; set; }
        public uint GhostKills { get; set; }
        public uint SurvivedWithNoKills { get; set; }
        public uint Revives { get; set; }
        public uint TriggerBombKills { get; set; }
        public uint TriggerBombsLost { get; set; }
        public uint DroppedArrowKills { get; set; }
        public uint HyperArrowKills { get; set; }
        public uint HyperDeaths { get; set; }
        public uint HyperSelfKills { get; set; }
        public uint HyperStomps { get; set; }
        public uint BombsDefused { get; set; }
        public uint EnemyInPrismKills { get; set; }
        public uint SelfInPrismKills { get; set; }
        public uint EnemyInTeamPrismKills { get; set; }
        public uint BombTrapKills { get; set; }
        public uint CrushOthersKills { get; set; }
        public uint KillsDuringMiasma { get; set; }
        public uint DuckDances { get; set; }
        public float LongestShot { get; set; }
        public float FastFallFrames { get; set; }
        public float DuckFrames { get; set; }
        public float LedgeFrames { get; set; }
        public float FramesAlive { get; set; }
        public KillStats Kills { get; set; }
        public KillStats Deaths { get; set; }
    }
}
